# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: required

dist: trusty

addons:
  postgresql: "9.5"

before_install:
  - sudo apt-get install --yes libgdal1h libgeos-c1 liblwgeom-2.3-0 libudunits2-dev
  - sudo apt-get install --yes postgresql-9.5-postgis-2.3
  - sudo service postgresql restart
  - psql -U postgres -c "create extension postgis;"
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

# We use clang, --without-libtool and --with-debug for faster build
#compiler:
#  - clang

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown

r_github_packages: 
  - jimhester/covr
