language: r

sudo: required

dist: trusty

addons:
  postgresql: "9.4"
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos++-dev

before_install:
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"

warnings_are_errors: false

r_packages: roxygen2

r_github_packages: 
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
