language: r
sudo: required
dist: trusty
cache: packages
latex: false
r:
  - release
  #- oldrel
#  - devel

addons:
  #postgresql: "9.6"
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
      - libprotobuf-dev
      - protobuf-compiler
      - libv8-3.14-dev
      - libjq-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libjson-c-dev
      - postgresql-9.6
      - postgresql-9.6-postgis-2.3
      - postgresql-contrib-9.6
      - postgresql-9.6-postgis-scripts
      - postgis

before_install:
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

warnings_are_errors: true

after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  #- Rscript -e 'covr::codecov()'
