language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: true
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8
      brew_packages: gdal2
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      brew_packages: gdal2
      latex: false

addons:
  postgresql: "9.4"
  apt:
    packages:
      - valgrind

before_script:
  - psql -U postgres -c "create extension postgis"

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then createdb postgis; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then psql -d postgis -c "CREATE EXTENSION postgis;"; fi
  - export CURWD=`pwd`
  - sudo apt-get install libproj-dev libgeos++-dev
  - cd
  - wget http://download.osgeo.org/gdal/2.0.2/gdal-2.0.2.tar.gz
  - tar zxf gdal-2.0.2.tar.gz
  - cd gdal-2.0.2
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd $CURWD

sudo: required

warnings_are_errors: true

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown

r_github_packages: 
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
