before_install:
  - sudo apt-get install libproj-dev libgeos++-dev postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - echo $USER
  - export CURWD=`pwd`
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd $CURWD

language: r

sudo: required

warnings_are_errors: false

r_packages: roxygen2

r_github_packages: 
  - edzer/rgdal2
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
