addons:
  postgresql: "9.4"
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos++-dev

before_script:
  - psql -U postgres -c "create extension postgis"

before_install:
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - sudo apt-get install libgdal-dev libproj-dev libgeos++-dev

language: r

sudo: required

warnings_are_errors: false

r_packages: roxygen2

r_github_packages: 
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
