language: r

cache: packages

sudo: required

dist: trusty

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get install libudunits2-dev aptitude
  - sudo apt-get remove libgeos-c1
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgdal-dev
  - # install postgis:
  - wget https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa/+files/libsfcgal1_1.2.2-1~trusty2_amd64.deb
  - sudo dpkg -i libsfcgal*deb
  - wget https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa/+files/liblwgeom-2.2-5_2.2.2+dfsg-2~trusty0_amd64.deb
  - sudo dpkg -i liblw*deb
  - wget https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa/+files/postgis_2.2.2+dfsg-2~trusty0_amd64.deb
  - sudo dpkg -i postgis*deb
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

warnings_are_errors: true

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown

r_github_packages: 
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
