language: r

cache: packages

sudo: required

dist: trusty

addons:
  postgresql: "9.6"

before_install:
  - sudo apt-get install libudunits2-dev postgis aptitude
  - sudo apt-get remove libgeos-c1
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo aptitude install -y libproj-dev libgdal-dev
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

warnings_are_errors: true

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown

r_github_packages: 
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
